# Generated by Django 5.0.7 on 2024-07-28 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('last_active_at', models.DateField()),
            ],
        ),
    ]
